---
- name:  Programmatically set firewall ports based on host instance number. 
  hosts: localhost 
  vars:
    instance_number: 99 
  become:  true
  
  tasks:
    - name: Set port 1128 manually 
      firewalld:
        port: "{{ instance_number }}28/tcp"
        permanent: true
        state: disabled
      notify:
        - restart firewalld

  handlers:
    - name: restart firewalld 
      systemd: 
        name: firewalld 
        state: restarted

